# -*- coding: utf-8 -*-
"""YellowStoneHM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJXo8xHTs2MHh5nvICwEH9Bs1pf_DsVZ
"""

import pandas as pd

URL = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
df = pd.read_csv(URL)

df.head()

pt = df.pivot_table(index='variety', 
               values=['sepal.length',	'sepal.width',	'petal.length',	'petal.width'], 
               aggfunc=['mean', 'median'])
pt

import csv

rows = []
for v in pt.index:
    row = {'variety': v}
    for k1 in ['mean', 'median']:
        for k2 in ['sepal.length',	'sepal.width',	'petal.length',	'petal.width']:
            k1_ = k1.replace('mean', 'average')
            k2_ = k2.replace('.', '_')
            row[f'{k1_}_{k2_}'] = round(pt[k1][k2][v], 5)
    print(row)
    rows.append(row)

with open('iris.csv', 'w', newline='') as csvfile:
    fieldnames = list(rows[0].keys())
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for row in rows:
        writer.writerow(row)